version: 2.1
jobs:
  build:
    working_directory: ~/backend
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - checkout
      - run: sudo composer self-update --1
      - restore_cache:
          key: composer-v1-{{ checksum "backend/composer.json" }}
      - run:
          command: composer install -n --prefer-dist
          working_directory: backend
      - save_cache:
          key: composer-v1-{{ checksum "backend/composer.json" }}
          paths:
            - vendor
      - restore_cache:
          key: npm-v1-{{ checksum "backend/package-lock.json" }}
      - run:
          name: npm ci
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
          working_directory: backend
      - save_cache:
          key: npm-v1-{{ checksum "backend/package-lock.json" }}
          paths:
            - node_modules
      # - run:
      #     command: npm ci
      #     working_directory: backend
      - run:
          command: npm run dev
          working_directory: backend
      - run:
          name: php test
          command: vendor/bin/phpunit
          working_directory: backend